query:
- 2009011:
  - olive
  - oil
  - health
- 2009036:
  - notting
  - hill
  - film
  - actors
- 2009067:
  - probabilistic
  - models
  - in
  - information
  - retrieval
- 2009073:
  - web
  - link
  - network
  - analysis
- 2009074:
  - web
  - ranking
  - scoring
  - algorithm
- 2009078:
  - supervised
  - machine
  - learning
  - algorithm
- 2009085:
  - operating
  - system
  - mutual
  - exclusion
run:
  b: 0.5
  d: 1
  data:
    file: data/data.json
    overwrite: true
    path: data/coll
  granularity: element
  k: 0.5
  limit: 1500
  num: 10
  staff:
  - Guillaume
  - Benoit
  - Gauthier
  - Theo
  step: 6
  weighting: bm25
